import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, FastAPI, HTTPException, Query
from pydantic import BaseModel, Field

from salesflow.analytics import queries
from salesflow.config import DB_PATH, REPORTS_DIR
from salesflow.logging_config import configure_logging

logger = configure_logging()
app = FastAPI(
    title="SalesFlow ETL Analytics API",
    version="1.0.0",
    description="Read-only analytics generated by the SalesFlow PySpark ETL pipeline.",
)


class HealthResponse(BaseModel):
    status: str
    database: str


class SummaryResponse(BaseModel):
    total_revenue: float
    total_orders: int
    average_order_value: float
    total_discount: float
    cancelled_orders: int
    unique_customers: int


class ProductSummary(BaseModel):
    product_id: str
    product_name: str
    category: str
    orders: int
    units_sold: int
    net_revenue: float


class GroupedRevenue(BaseModel):
    category: str | None = None
    state: str | None = None
    revenue: float


class MonthlyRevenue(BaseModel):
    month: str
    revenue: float


class QualityReport(BaseModel):
    validation_timestamp: str
    total_records: int
    valid_records: int
    rejected_records: int
    failed_checks: list[str]
    quality_score: float = Field(ge=0, le=100)
    checks: list[dict[str, Any]]


def _ensure_database() -> None:
    if not DB_PATH.exists():
        raise HTTPException(
            status_code=503,
            detail="Analytics database is not available. Run python run_pipeline.py first.",
        )


router = APIRouter()


@router.get("/health", response_model=HealthResponse)
def health() -> HealthResponse:
    return HealthResponse(status="ok", database="ready" if DB_PATH.exists() else "not_ready")


@router.get("/healthz", response_model=HealthResponse)
def healthz() -> HealthResponse:
    return health()


@router.get("/analytics/summary", response_model=SummaryResponse)
def analytics_summary() -> dict[str, float | int]:
    _ensure_database()
    return queries.summary(DB_PATH)


@router.get("/analytics/top-products", response_model=list[ProductSummary])
def analytics_top_products(limit: int = Query(default=10, ge=1, le=100)) -> list[dict[str, Any]]:
    _ensure_database()
    return queries.top_products(DB_PATH, limit)


@router.get("/analytics/revenue-by-category", response_model=list[GroupedRevenue])
def analytics_revenue_by_category() -> list[dict[str, Any]]:
    _ensure_database()
    return queries.revenue_by_category(DB_PATH)


@router.get("/analytics/revenue-by-state", response_model=list[GroupedRevenue])
def analytics_revenue_by_state() -> list[dict[str, Any]]:
    _ensure_database()
    return queries.revenue_by_state(DB_PATH)


@router.get("/analytics/monthly-revenue", response_model=list[MonthlyRevenue])
def analytics_monthly_revenue() -> list[dict[str, Any]]:
    _ensure_database()
    return queries.monthly_revenue(DB_PATH)


@router.get("/quality/report", response_model=QualityReport)
def quality_report() -> dict[str, Any]:
    report_path = REPORTS_DIR / "quality_report.json"
    if not report_path.exists():
        raise HTTPException(status_code=503, detail="Quality report is not available. Run the pipeline first.")
    return json.loads(report_path.read_text(encoding="utf-8"))


app.include_router(router)
app.include_router(router, prefix="/api")